Add several themes
WyriHaximus/awesome-phpstorm pull request #31
Opened 2020-12-09 11:05 UTC by DuboisS

2020-12-11 06:36 UTC, bueltge requested changes

2020-12-11 06:36 UTC, bueltge commented on README.md
> +* [One Dark](https://plugins.jetbrains.com/plugin/11938-one-dark-theme) - Add the [One Dark theme](https://github.com/one-dark/jetbrains-one-dark-theme) look to your IDE.
Missing an s on `Add`?

2020-12-11 08:16 UTC, bueltge approved these changes

2020-12-12 19:09 UTC, WyriHaximus approved these changes

2020-12-12 19:09 UTC, merged

2020-12-12 19:10 UTC, WyriHaximus commented
Thanks 👍